# Generated by Django 3.2.12 on 2022-10-18 06:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_employeetable_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetable',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('eca0fbca-decc-46a0-bfff-ec78a7381839'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TimingCreateTable',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('eca0fbca-decc-46a0-bfff-ec78a7381839'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('timing', models.DateField()),
                ('EmployeeTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeetable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
