# Generated by Django 3.2.12 on 2022-10-18 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_auto_20221018_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timingcreatetable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a0be52aa-b033-4a38-a90e-467f759f4315'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timingcreatetable',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a0be52aa-b033-4a38-a90e-467f759f4315'), editable=False, primary_key=True, serialize=False),
        ),
    ]
